### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by Peccata54** [IBM/event-streams#11]
Error installing Event Streams 1.0 on ICP 3.1.0.   Container config errors reported.  kafka and some others get the error message:
 Error: secrets "eventsgreen-ibm-es-oauth-secret" not found
and/or 
Error: Couldn't find key eventstreams-eventsgreen-api-key in Secret streaming/eventsgreen-ibm-es-iam-secret
Both these secrets exist. The data in the oauth secret looks good.  The Iam-secret contains the annotation for the api-key. 
The OS is ubuntu
Event Streams is the dev version off the IBM catalog

**Comment by EmmaHumber** [comment]
HI @Peccata54   

An install will show a events similar to
```
 Warning  Failed     2m               kubelet, 10.51.4.144  Error: secrets "elh8c-ibm-es-oauth-secret" not found
```
early in the install process as the secret has not yet been created at this point in the install.  This doesn't always mean that there is a problem with the installation.

What is the symptom you are seeing? For example, does a `kubectl get pods` show everything in running and ready state, or are some of the containers reporting that they are in an error state or not ready - for example the container config you mention above?  

If the pods aren't all healthy, could you copy in the output of `kubectl get pods` so we can take a look at what's up.  For any unhealthy pods also include a `kubectl describe pod`

Thanks
Emma

**Comment by Peccata54** [comment]
Thank you.. The deployment shows as a failed Helm deployment on the admin panel.  
[EventsGetPods.txt](https://github.com/IBM/event-streams/files/2621589/EventsGetPods.txt)
i have attached the get pods output as well as Describe Pod output for one of the kafka brokers and a proxy pod.
[KafkaPodDescribe.txt](https://github.com/IBM/event-streams/files/2621594/KafkaPodDescribe.txt)
[EventsProxyPod.txt](https://github.com/IBM/event-streams/files/2621595/EventsProxyPod.txt)

**Comment by Peccata54** [comment]
sorry closed by mistake...

**Comment by EmmaHumber** [comment]
Hi 

Thanks for the info.  I've got a few follow on questions.

I can see from the get pods output this data was collected after about 3 minutes.  It can take a little while longer than that for everything to come up, so I wanted to confirm that things don't sort themselves out if you wait, say, 10 minutes.

How many times have you attempted the install?  Is this the first attempt, or do the pods fail to start up in the same way every time?

I'd like to see the content of the iam secret please - remember to *** out the two hashed values before posting

```
 kubectl get secret RELEASE-ibm-es-iam-secret -o json

```

I'm looking for two lines in the information returned, I know above you mention these are present but I'd like to check the format:

```
"data": {
        "eventstreams-RELEASE-api-key": "****",
        "eventstreams-RELEASE-service-id": "****"
    },
```
If they are missing, then unfortunately the only option is likely to be a reinstall.


The api keys in this secret are populated by an ICP process, which runs in kube-system.  Could you run the following and post the output:

```
kubectl get pods -n kube-system | grep auth-apikeys
```

I'd be interested in the status, age and restart count of the returned pod.

**Comment by Peccata54** [comment]
Thank you.  The install has been deleted and reinstalled several times.  It fails each time in the same way.

I have attached the iam-secret output.   There are no data fields in the output. 

The get pods output is:
[ironman@oc0008287310 ~]$ kubectl get pods -n kube-system | grep auth-apikeys
auth-apikeys-sz9mp                                              1/1       Running   0          13d
auth-apikeys-tdtrw                                              1/1       Running   0          13d
auth-apikeys-zntvx                                              1/1       Running   0          13d
[green-iam-secret.txt](https://github.com/IBM/event-streams/files/2626693/green-iam-secret.txt)

**Comment by EmmaHumber** [comment]
The Event Streams pods are failing to start up because the two lines in the data stanza in the iam secret are missing.

As mentioned above, Event Streams doesn't write these two lines, we rely on ICP to add them in to the secret, and my understanding is that this is done by the auth-api pod.

It's interesting to see there are three instances of  auth-apikeys pods returned on your system.  On my system (also a 3.1.0 ICP install) there is only a single instance.  Does a kubectl describe of each pod show anything of interest?

There are logs available in an auth-apikeys pod under the /opt/ibm/CloudIAM-APIKeys/run_localwlp/target/liberty/wlp/usr/servers/defaultServer/logs folder on the container, but rather than ask you to collect them, I'm going to get in touch with my ICP colleagues to see what they suggest as a next step here.

In the interim, I'm wondering if attempting to install using a different release name might help?

**Comment by Peccata54** [comment]
to be clear.. I didn't delete the data portions of the secret output.. they are just not there.  What I sent is the entire output of the command

**Comment by EmmaHumber** [comment]
Hi - yes I understood from the explanation that the entries were missing.  Thanks for confirming.  I just need to work to understand why they are not being inserted by the ICP process that should automatically insert them

I've posted the question to ICP, and I'll let you know what response comes back when I get it.

**Comment by EmmaHumber** [comment]
HI @Peccata54 

Could you supply the output of 

kubectl -n kube-system

and

kubectl logs secret-watcher-UNIQUE-ID -n kube-system

Thanks

**Comment by Peccata54** [comment]
neither of those commands function. I think you are missing the verb in the first one.

I'm not sure what to substitute for the secret-watcher-UNIQUE-ID in the 2nd one?

**Comment by Peccata54** [comment]
I think you are looking for the logs for a specific pod.

**Comment by EmmaHumber** [comment]
Sorry,  I meant to type:

```
kubectl -n kube-system get pods
```

That should return a long list of pods - could you copy the output into this issue.  One of the pods returned should be called something like the following:

```
secret-watcher-6c55bb5d79-lprmc
```

where 6c55bb5d79-lprmc is the unique string for your instance of the pod.

I'm after the kubctl logs for the single container in that pod (there's only 1 so no need to specify container name). On my system that would be:

kubectl logs secret-watcher-6c55bb5d79-lprmc -n kube-system

**Comment by Peccata54** [comment]
thank you. i have attached the files... I notice there is a panic noted in the logs

[SecretLogs.txt](https://github.com/IBM/event-streams/files/2635213/SecretLogs.txt)
[Kube-System-Get-Pods.txt](https://github.com/IBM/event-streams/files/2635214/Kube-System-Get-Pods.txt)

**Comment by EmmaHumber** [comment]
Thanks - I've passed the logs on to the ICP team, I'll let you know what they say.

**Comment by EmmaHumber** [comment]
Hi - Sorry for the delay in replying.  

The ICP team are hoping a pod restart will resolve the issue:

kubectl delete pod secret-watcher-6c55bb5d79-lprmc -n kube-system

(replace the 6c55bb5d79-lprmc with the unique string for your deployment).

Once the pod has come up, take a look at the logs to see if the panic is listed again, and copy it into this issue if it is.

Please also try a reinstall of Event Steams after the restart of the pod and let me know how you get on with that.

If this doesn't fix the problem they suspect some DNS based issues.  If that's the case we'll work out the next steps to progress this.

Thanks

**Comment by Peccata54** [comment]
Hi.  Restarting the secret watcher pod seems to have solved that problem.  I reinstalled events and it deployed.  Thank you so much.

Two quick questions.  It came up with only one of the three brokers, the other two show pending. Will it function with only one broker online?
I think the other two brokers didn't come up due to resource constraints (I have only 4 worker nodes, and possibly memory limits).

When I run describe on a pending pod I get:

Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  4m (x600 over 14m)  default-scheduler  0/12 nodes are available: 3 Insufficient memory, 9 node(s) had taints that the pod didn't tolerate.

So I'm wondering if I can run it like this for test purposes or do you expect I will run into strange behavior?

Again thanks so much for the help

**Comment by EmmaHumber** [comment]
Hi @Peccata54   

Glad to hear the restart of the secret watcher pod helped.

4 worker nodes should be fine, I usually run with 3 workers.  It sounds like there is insufficient memory available; do you have any scope to be able increase this?

A kubectl get nodes will give you a list of nodes in your system, then you can do a kubectl describe NODE-IP to get more information on where the memory limits are being hit.

In the current state I think you're likely to get unpredictable behaviour, especially as from your description of the number of pods failing to start it seems that more than just the Kafka brokers are in pending state.

The other thing you could try is when installing, scroll down to the bottom of the configuration page and de-select the "Enable message indexing" box.  You won't be able to view messages in the UI unless you look at specific offsets, but you might free up some space for resources.

Let me know how you get on.

**Comment by Peccata54** [comment]
Hi. Thank you again.  I added some memory to the worker node virtual machines (made them 32G) and also added virtual CPUs (from 8 to 12).  Did a clean install and all looks good.
