### ISSUE TITLE
Is the Kafka REST API available for ICP EventStreams?

### ISSUE THREAD

**Issue by robomeister** [IBM/event-streams#14]
I've noticed the Kafka REST API is available in our cloud EventStreams offering:

https://console.bluemix.net/docs/services/EventStreams/eventstreams025.html#rest_using 

Is it also available for the ICP offering?  Thanks!

**Comment by EmmaHumber** [comment]
Hi Rob, this REST API isn't supported for use in the on-prem ICP offering, please use the Event Streams CLI or UI to administer your Event Streams Kafka cluster.

**Comment by robomeister** [comment]
Thanks.  Any chance it's in the roadmap?

**Comment by EmmaHumber** [comment]
Hi Rob - as discussed via email.  Do you mind if I close this off?  Reopen if you need more information.
