### ISSUE TITLE
Unable to configure TLS between Openshift Serverless and IBM Event Streams

### ISSUE THREAD

**Issue by jeanabraham** [IBM/event-streams#155]
HI,

I'm trying to [configure TLS](https://docs.openshift.com/container-platform/4.6/serverless/serverless-kafka.html#serverless-configuring-tls-authentication-against-an-apache-kafka_serverless-kafka) between the Knative Broker and IBM Event Streams as the Kafka provider. I was able to create the Service ID but trying to figure out the right way to generate the .pem file to connect to the bootstrap servers. Please advise.

Thanks.

**Comment by samuel-hawker** [comment]
Hi @jeanabraham,
Our documentation should cover most use cases of how you can configure a Kafka Client, in this case the Knative Broker, to IBM Event Streams:
https://pages.github.ibm.com/mhub/qp-docs/getting-started/connecting/

Can I ask what version of Event Streams you are running, as documentation between versions can vary slightly.
