### ISSUE TITLE
SASL authentication errors when connecting to Event Streams installed on an IBM Cloud Private cluster that has custom certificates

### ISSUE THREAD

**Issue by nictownsend** [IBM/event-streams#19]
## Issue Description
The following error is seen after install after logging into the Event Streams UI, or when initiating Kafka connections:
```org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed, invalid credentials```

Checking the logs for an `access-controller` pod (`kubectl logs <release>-ibm-es-access-controller-<id>`) shows:
  ```
  {"error":"Post https://xxx.yyy.zzz:8443/iam-token/oidc/token: x509: certificate signed by unknown authority","message":"failed to obtain token from IAM","message_template":"failed to obtain token from IAM","mh_file":"renewer.go","mh_line":104,"mh_ts":"Feb  6 07:53:09.287","transaction_id":"a8411f35-bde7-4524-9cf3-73972746908c"}
  ```

This can occur when IBM Event Streams is installed on an IBM Cloud Private (ICP) that was [installed with custom certificates](https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.1/installing/create_ca_cert.html).

## Issue Resolution
Not yet available

## Workaround
After installing Event Streams, a Kubernetes secret containing the certificate used to verify connections from Event Streams to ICP must be updated to contain the correct certificate to verify the custom `icp-router` certificate supplied on install of ICP.

- Copy the proxy secret onto your local machine: ```kubectl -n <event-streams-namespace> get secret <release-name>-ibm-es-proxy-secret --export -o yaml > proxy-secret.yaml```
- Copy `proxy-secret.yaml` to `proxy-secret.bak` so that you have a backup of the secret
- Replace the value `tls.cluster` inside `proxy-secret.yaml` with the certificate needed to verify the `icp-router` certificate. The certificate must be in PEM format, encoded as a base64 string. `base64 <cert.pem>`
  - If the `icp-router` certificate is self signed, provide the certificate itself as the value for `<cert.pem>`. If the `icp-router` certificate is signed by a chain of certificate authorities, provide the chain in a single file as the value for `<cert.pem>`. The chain file will look the following:
   ```
   -----BEGIN CERTIFICATE----- 
   (Your Intermediate certificate: CA.crt) 
   -----END CERTIFICATE----- 
   -----BEGIN CERTIFICATE----- 
   (Your Root certificate: TrustedRoot.crt) 
   -----END CERTIFICATE-----
   ```
- Apply the secret ```kubectl -n <event-streams-namespace> apply -f proxy-secret.yaml```
- Gracefully restart the `access-controller` and `rest` pods by scaling the deployments:
  -  ```kubectl -n <event-streams-namespace> scale deploy <release-name>-ibm-es-access-controller-deploy --replicas 0``` 
  - ```kubectl -n <event-streams-namespace> scale deploy <release-name>-ibm-es-access-controller-deploy --replicas 2```
  -  ```kubectl -n <event-streams-namespace> scale deploy <release-name>-ibm-es-rest-deploy --replicas 0``` 
  - ```kubectl -n <event-streams-namespace> scale deploy <release-name>-ibm-es-rest-deploy --replicas 1```

## Fix details
IBM Internal issue number - 2514
Fix target -

**Comment by EmmaHumber** [comment]
For the above workaround to be effective the certificate supplied in the step in the third bullet point, which is used to verify the icp-router certificate, requires the IP address of the external access point for the cluster (generally the ICP Proxy) in the list of Subject Alternative Names (SANs).  

The workaround above will not work if only the fully qualified domain name (FQDM) is included in this list.

**Comment by EmmaHumber** [comment]
This issue is resolved by changes made to how internal certificate are generated in ICP 3.2  so there will be no code fix available for Event Streams itself.  

The resolution is to move to using ICP 3.2 or later, which is now available.
