### ISSUE TITLE
Calling eventstreams UI on ICP 3.1.1 with correct dns name fails

### ISSUE THREAD

**Issue by johbossle** [IBM/event-streams#20]
Hi, 
I installed IBM Event Streams Community Edition-2018.3.1 into a fresh installation of ICP 3.1.1 (CE) and now I am not able to call the UI via my registered hostname for the proxy. The browser states that there is no valid connection possible, since the page is protected by HSTS.
Calling the UI via the IP of the proxy server works - with the limitation that the issued certificate is not valid.
For the installation I used following part of the values.yaml:
```
proxy:
  # external IP address for access that the proxy should use
  externalEndpoint: "xxx.yyy.zzz"
# Secure connection settings for the proxy
tls:
  type: "provided"
  key: "<key for my certificate | base 64>"
  cert: "<my wildcard certificate without the chain | base 64>"
  cacert: "<the chain parts of my wildcard certificate | base 64>"
```
The tracing of the curl returns to the folllowing output:
[curl.trace.txt](https://github.com/IBM/event-streams/files/2844371/curl.trace.txt)

The presented certificate for the endpoint is a self-signed/self created certificate for the endpoint that enumerates all necessary alternative names in the correct way, but is not signed by the CA that was specified during the installation (also see #19). The presented certificate is located at `kubectl get secret eventstreams-ibm-es-proxy-secret -o=jsonpath='{.data.https\.cert}'` with the following partial output:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1549454351754155924 (0x1580c48607fd5794)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=New York, L=Armonk, O=IBM Cloud Private, CN=www.ibm.com
        Validity
            Not Before: Feb  6 11:59:11 2019 GMT
            Not After : Feb  3 11:59:11 2029 GMT
        Subject: O=IBM, OU=IBM Event Streams
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b5:eb:3b:54:93:0f:cd:26:98:a1:65:96:19:22:
                    32:c3:09:3b:1c:0a:a4:e6:c9:98:32:1c:17:a2:b9:
                    63:9b:33:9a:e8:e6:72:60:df:7d:23:51:89:5c:a2:
                    63:e9:06:74:0c:8a:05:43:79:6f:02:e2:55:a3:af:
                    f3:d1:bb:07:20:4d:de:db:98:a0:5a:db:e7:09:89:
                    d7:f1:ba:29:93:cd:da:34:8c:a8:60:03:78:d2:80:
                    4e:c1:2e:b5:2b:34:d6:c5:59:b7:cb:ba:61:99:e5:
                    e1:fb:b5:f3:bf:a4:21:7b:fb:45:53:d4:46:1a:67:
                    b4:ad:08:bc:ec:67:c5:db:10:c4:0e:de:05:ac:7e:
                    3c:9e:13:0e:a6:a0:eb:9a:e2:ba:9d:68:3a:05:01:
                    f2:1d:b7:5c:6b:60:ad:c6:6a:d7:93:d1:0f:01:a0:
                    7c:de:9a:b3:6a:9f:0c:49:5f:84:58:ee:51:31:91:
                    7f:e6:84:24:5e:87:50:5d:d8:e1:75:5f:02:66:10:
                    23:a1:e0:73:c3:c4:f8:7f:dd:3b:67:80:88:dd:2f:
                    97:b9:08:aa:1e:30:1c:f3:8a:d8:da:95:af:1b:89:
                    e1:54:62:bc:80:6c:11:ef:1e:c6:60:42:6a:b9:ff:
                    4a:33:9a:ad:c6:59:d5:32:6c:37:ab:d7:35:97:fe:
                    bf:55
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier: 
                keyid:00:EE:E8:1D:2E:C4:52:D4:FC:A3:27:ED:C6:94:64:18:A6:33:86:A5

            X509v3 Subject Alternative Name: 
                DNS:yyy.zzz, DNS:xxx.yyy.zzz, DNS:yyy.zzz.eventstreams-ns.svc.cluster.local, DNS:xxx.yyy.zzz, IP Address:123.456.12.123
```
The signer corresponds to the previous (see #18) used certificate specified in `tls.cluster`.

Do you have any ideas to overcome this issue?

**Comment by nictownsend** [comment]
Hi Johannes,

Please could you try the following:

1. `kubectl -n <event-streams-namespace> get secret <event-streams-release>-ibm-es-proxy-secret --export -o yaml > proxySecret.backup.yaml`
2. Copy `proxySecret.backup.yaml` to `proxySecret.yaml`
3. Edit `proxySecret.yaml` and copy the values stored in `tls.key` to `https.key`, and `tls.cert` to `https.cert`
* Apply the updated secret - `kubectl -n <eventStreamsNamespace> apply -f proxySecret.yaml`
* Scale down and up the UI deploy: `kubectl -n <eventStreamsNamespace>  scale deploy <eventStreamsRelease>-ibm-es-ui-deploy --replicas=0` and then `kubectl -n <eventStreamsNamespace>  scale deploy <eventStreamsRelease>-ibm-es-ui-deploy --replicas=1` to restart the UI.

**Comment by johbossle** [comment]
Hi Nic,

thank you again for your support. The issue is solved now by replacing those certificates as well.
Kind regards

**Comment by nictownsend** [comment]
@johbossle You may also encounter the following issue: https://github.com/IBM/event-streams/issues/22. I have included a workaround in the issue if you are affected.
