### ISSUE TITLE
kafka-python-console-sample

### ISSUE THREAD

**Issue by NeilHill** [IBM/event-streams#26]
Hi,

I'm trying to get the python sample script working, it builds ok and attempts to send the messages but I only ever get timeouts on the delivery report.

I'm running this from a Ubuntu 19.04 with Python 3.7.2.

This is more than likely going to be something to do with the input strings I'm specifying but I can't see anything wrong with them, input below;

`python app.js "kafka05-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka01-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka02-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka04-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka03-prod02.messagehub.services.eu-gb.bluemix.net:9093"
"https://kafka-admin-prod02.messagehub.services.eu-gb.bluemix.net:443"
"<My API Key>"
"/etc/ssl/certs"`

Logging outputs below;

Using command line arguments to find credentials.
Kafka Endpoints: kafka05-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka01-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka02-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka04-prod02.messagehub.services.eu-gb.bluemix.net:9093,kafka03-prod02.messagehub.services.eu-gb.bluemix.net:9093
Admin REST Endpoint: https://kafka-admin-prod02.messagehub.services.eu-gb.bluemix.net:443
Creating the topic start-action-chain-for-api-call with Admin REST API
{"errorCode":42201,"errorMessage":"Topic \"my-topic\" already exists."}
Admin REST Listing Topics:
[{"name":"my-topic","partitions":1,"retentionMs":86400000,"cleanupPolicy":"delete","markedForDeletion":false}]
This sample app will run until interrupted.
The producer has started
Sending message This is a test message #0
Sending message This is a test message #1
Sending message This is a test message #2
Sending message This is a test message #3
Sending message This is a test message #4
Sending message This is a test message #5
Delivery report: Failed sending message b'This is a test message #0'
KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
Delivery report: Failed sending message b'This is a test message #1'
KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
Delivery report: Failed sending message b'This is a test message #2'
KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
Delivery report: Failed sending message b'This is a test message #3'
KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
Delivery report: Failed sending message b'This is a test message #4'
KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
Delivery report: Failed sending message b'This is a test message #5'
KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}

**Comment by EmmaHumber** [comment]
Hi Neil - Nic already replied to you via our Slack channel, but to close the thread here too.

It looks like you're pointing against the IBM Cloud Event Streams - please could you try following through the recommended channels here for troubleshooting : https://cloud.ibm.com/docs/services/EventStreams?topic=eventstreams-troubleshooting
