### ISSUE TITLE
Missing Documentation for Schema API

### ISSUE THREAD

**Issue by snaum** [IBM/event-streams#30]
## Schema API documentation page is 404

https://ibm.github.io/event-streams/schemas/schema-api-reference/

**Comment by samuel-hawker** [comment]
Hello @snaum, thank you so much for letting us know!
We will aim to fix this soon, in the meantime you can find the schema JavaDoc here: https://ibm.github.io/event-streams/schema-api/ which can be found in the `APIs` dropdown in the documentation.

You can also use our CLI provided with Event Streams to interact with schemas.

**Comment by gabortpubs** [comment]
Thanks for reporting this issue, this is now fixed:
https://ibm.github.io/event-streams/schemas/overview/#serialization-and-deserialization
