### ISSUE TITLE
REST producer API rejecting messages with size > 65KB

### ISSUE THREAD

**Issue by katheris** [IBM/event-streams#40]
## Issue Description

When sending messages to the REST producer API the response code is 400 Bad Request. Additionally when the `Accept` header in the request is set to `application/json` the response includes the message: `Error parsing JSON message: http: request body too large`.

The REST producer API has a configured limit for both message and key size. This defaults to 4096 bytes for the key and 65536 bytes for the message. The request is being rejected because the message body sent is larger than the limit.

## Issue Resolution

The Event Streams Helm chart has been updated to allow configuration of the max message and key size at install time.

## Workaround

The limits can be updated as follows:

If required initialise kubectl configuration:
1. Ensure you have the Event Streams CLI installed.
2. Log in to your cluster as an administrator by using the IBM Cloud Private CLI: `cloudctl login -a https://<cluster_address>:<cluster_router_https_port>`
3. Run the following command to initialize the Event Streams CLI: `cloudctl es init`
4. If you have more than one Event Streams instance installed, select the one where the topic you want to produce to is.
Details of your Event Streams installation are displayed.
 
Update the size limit(s):
1. List the Event Streams deployments: `kubectl get deployments`
2. Identify the rest-producer deployment from the list (it will be similar to ***-ibm-es-rest-producer-deploy)
3. Edit the rest-producer deployment: kubectl edit deployment `***-ibm-es-rest-producer-deploy`
4. In the yaml file locate the `env` section for the rest-producer container under `spec.template.spec.containers`
5. Add the following environment variables as required:
  a. MAX_KEY_SIZE - maximum key size in bytes (default 4096)
  b. MAX_MESSAGE_SIZE - maximum message size in bytes: (default 65536)
6. Save the change and wait for the REST producer pod to be updated

**Note:**
Sending larger requests to the REST producer will result in some increase in latency, since it will take the REST producer longer to process the requests. Do not set the limit to higher than the broker max message size, otherwise Kafka will reject the messages. The default for Kafka is 1000012 bytes.

## Environment

* Affected IBM Event Streams Versions: 2019.1.1, 2019.2.1, 2019.4.1
* Internal issue number: 4394, 5386

**Comment by gabortpubs** [comment]
Documented how to configure limits in 2019.4.2:
https://ibm.github.io/event-streams/2019.4/connecting/rest-api/#key-and-message-size-limits
and 
https://ibm.github.io/event-streams/2019.4/installing/configuring/#-rest-producer-api-settings

**Comment by gabortpubs** [comment]
Fixed in: 2019.4.2
