### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by mcdonnibm** [IBM/event-streams#5]
## Issue Description

* Describe the problem
* Describe the application flow or what steps were being taken when the problem occurred
* If the issue is reproducible provide a set of instructions describing how to reproduce it, including screenshots if they might assist
* Include any error messages, stack traces and logs associated with the error, in full, in text format (ie not a screenshot)
* Describe the expected behaviour
* Did this used to work? If so what has changed, for example was any maintenance of the system performed?

## Environment

* IBM Event Streams Version:
* IBM Cloud Private (ICP) Version:
* Operating system of ICP install: 
* Browser (for UI issues):

**Comment by dalelane** [comment]
@mcdonnibm Hi, thanks for trying Event Streams! 

It'd be useful to have more detail about the issue that you encountered - please can you add a comment with some of the info listed above? 

If you'd rather do it privately, you're welcome to email us at eventstreams@uk.ibm.com instead.

**Comment by mcdonnibm** [comment]
Sorry.  This was opened in error.
