### ISSUE TITLE
Download schema registry Java dependencies not working on 2019.4.2

### ISSUE THREAD

**Issue by kitd** [IBM/event-streams#90]
## Issue Description

* When I'm viewing a schema in the EventStreams UI, click on the `Connect to this version` blue button, and click on `Java Dependencies` link in paragraph `2. Download the schema registry dependencies ...`, the link fails with a network error.
* A workaround is to adjust the link to say `2019.4.1`, which produces files that work with 2019.4.2.
* Ie:
    `https://<my-eventstreams-ui-address>/api/files/java-dependencies/dependencies-2019.4.1-java.zip`

## Environment

* IBM Event Streams Version: 2019.4.2
* IBM Cloud Private (ICP) Version: any
* Operating system of ICP install: any
* Browser (for UI issues): any

**Comment by EmmaHumber** [comment]
Further details in the Event Streams troubleshooting [https://ibm.github.io/event-streams/2019.4/troubleshooting/schemaregistry-java-deps-download-error/](https://ibm.github.io/event-streams/2019.4/troubleshooting/schemaregistry-java-deps-download-error/)

**Comment by Steve-Dare** [comment]
Fixed by IBM internal issue 5970, closing.
